import { expect, test } from '@playwright/test';

// Single linear smoke that exercises the full SPA + reverse proxy + cookie auth
// path against the docker compose stack at http://localhost:8080. A unique
// email per run keeps the spec idempotent across local + CI reruns.
test('register -> CRUD -> DueToday -> toggle -> delete -> logout @smoke', async ({ page }) => {
  const email = `e2e-${Date.now()}@example.com`;
  const password = 'E2eTest!123';

  // 1. Unauthed root redirects to login.
  await page.goto('/');
  await expect(page).toHaveURL(/\/login/);

  // 2. Register a fresh user.
  await page.getByRole('button', { name: 'Register' }).click();
  await expect(page).toHaveURL(/\/register/);
  await expect(page.getByRole('heading', { name: /create account/i })).toBeVisible();
  await page.getByRole('textbox', { name: 'Email' }).fill(email);
  await page.getByRole('textbox', { name: 'Password' }).fill(password);
  await page.getByRole('button', { name: 'Register' }).click();
  await expect(page).toHaveURL(/\/todos$/);

  // 3. Create a todo due today.
  const today = new Date().toISOString().slice(0, 10);
  await page.getByRole('button', { name: 'New Todo' }).click();
  const newDialog = page.getByTestId('dialog-new-todo');
  await expect(newDialog).toBeVisible();
  await newDialog.getByRole('textbox', { name: 'Title' }).fill('E2E smoke todo');
  await newDialog.getByRole('textbox', { name: 'Description' }).fill('Generated by Playwright');
  await newDialog.getByRole('textbox', { name: 'Due Date' }).fill(today);
  await newDialog.getByRole('combobox', { name: 'Priority' }).selectOption('High');
  await newDialog.getByTestId('todo-create-submit').click();
  await expect(newDialog).toBeHidden();
  await expect(page.getByRole('heading', { name: 'E2E smoke todo' })).toBeVisible();

  // 4. DueToday tab includes it.
  await page.getByTestId('tab-duetoday').click();
  await expect(page).toHaveURL(/status=DueToday/);
  await expect(page.getByRole('heading', { name: 'E2E smoke todo' })).toBeVisible();

  // 5. Edit the title.
  const item = page.getByRole('listitem').filter({ hasText: 'E2E smoke todo' });
  await item.click();
  await item.getByRole('button', { name: 'Edit' }).click();
  const editDialog = page.getByTestId('dialog-edit-todo');
  await expect(editDialog).toBeVisible();
  await editDialog.getByRole('textbox', { name: 'Title' }).fill('E2E smoke todo (edited)');
  await editDialog.getByTestId('todo-edit-submit').click();
  await expect(editDialog).toBeHidden();
  await expect(page.getByRole('heading', { name: 'E2E smoke todo (edited)' })).toBeVisible();

  // 6. Toggle complete.
  const editedItem = page.getByRole('listitem').filter({ hasText: 'E2E smoke todo (edited)' });
  await editedItem.click();
  await editedItem.getByRole('button', { name: /complete/i }).click();
  await expect(editedItem.getByText('Complete', { exact: true })).toBeVisible();

  // 7. Delete.
  await editedItem.click();
  const deleteButton = editedItem.getByRole('button', { name: 'Delete' });
  await expect(deleteButton).toBeEnabled();
  await deleteButton.click();
  const confirmDialog = page.getByTestId('dialog-delete-todo');
  await expect(confirmDialog).toBeVisible();
  await confirmDialog.getByTestId('todo-delete-confirm').click();
  await expect(page.getByRole('heading', { name: 'E2E smoke todo (edited)' })).toHaveCount(0);

  // 8. Sign out.
  await page.getByRole('button', { name: 'Logout' }).click();
  await expect(page).toHaveURL(/\/login/);
});
